name: run Python Json To MD Files

on:
  push:
    paths:
      - sources/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt
          
      - name: execute py scripts
        #env:
        #  SOME_SECRET: ${{ secrets.SOME_SECRET }}
        run: |
          python scripts/fish.py
          python scripts/wMastery.py
          
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)
          
      - name: Commit resized images
        env:
          TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
          git add .
          git commit -m "Auto-resized large images" || echo "No changes to commit"
          git push origin HEAD:${{ github.ref_name }}