name: run Python Json To MD Files

on:
  push:
    paths:
      - sources/**
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt
          
      - name: execute py scripts
        run: |
          python scripts/amitoi.py
          python scripts/fish.py
          python scripts/skills.py
          python scripts/wMastery.py
          
      - name: Commit generated Markdowns
        run: |
          git config --global user.name 'githubAction'
          git config --global user.email 'action@github.com'
          git add -A
          git commit -m "generated MD files by GithubActions" || true
          git push