name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install xmltodict
          pip install Pillow

      - name : resizing images
        run: |
          python scripts/resize_images.py

      - name: generate static .md files
        run: |
          python scripts/amitoi.py
          python scripts/fish.py
          python scripts/items.py
          # python scripts/skills.py
          python scripts/wMastery.py

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install fast-xml-parser glob fs-extra

      - name: Minify JSON/XML files with custom script
        run: node scripts/minifyFiles.js

      - name: Compress files in sources
        run: |
          mkdir -p compressed
          find minified-sources -type f ! -name '*.gz' | while read -r file; do
            gzip -c "$file" > "compressed/$file.gz"
          done

      - name: Prepare output for Pages (no write to repo)
        run: |
          rm -rf public
          mkdir -p public
          mkdir -p public/sources

          cp -r docs/* public/
          cp -r --parents Image/* public/
          cp -r compressed/* public/sources/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: ./public
          publish_branch: gh-pages
          force_orphan: true  # 💡 This makes sure gh-pages branch has no history or sync back
