name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install xmltodict
          pip install Pillow

      - name: converting xml files to json structure for weapons
        run: |
          python scripts/xmltojson.py

      - name : resizing images
        run: |
          python scripts/resize_images.py

      - name: generate static .md files
        run: |
          python scripts/amitoi.py
          python scripts/fish.py
          python scripts/items.py
          # python scripts/skills.py
          python scripts/wMastery.py

      - name: Prepare output for Pages (no write to repo)
        run: |
          rm -rf public
          mkdir -p public

          cp -r docs/* public/
          cp -r --parents Image/* public/
          cp --parents sources/Skills/cJson/* public/ || true

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: ./public
          publish_branch: gh-pages
          force_orphan: true  # 💡 This makes sure gh-pages branch has no history or sync back
